// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { createRequire } = require('node:module')
require = createRequire(__filename)

// On Windows, add the bundled lib\ directory to the DLL search path so that
// opencv_world*.dll shipped alongside this package is found automatically.
if (process.platform === 'win32') {
  try {
    const path = require('node:path')
    const libDir = path.join(__dirname, 'lib')
    if (require('node:fs').existsSync(libDir)) {
      // process.env.PATH is read by LoadLibrary on Windows.
      process.env.PATH = libDir + ';' + (process.env.PATH || '')
    }
  } catch (_) {}
}

const { readFileSync } = require('node:fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (typeof process.report?.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./node-opencv-rs.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('node-opencv-rs-android-arm64')
        const bindingPackageVersion = require('node-opencv-rs-android-arm64/package.json').version
        if (bindingPackageVersion !== '1.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./node-opencv-rs.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('node-opencv-rs-android-arm-eabi')
        const bindingPackageVersion = require('node-opencv-rs-android-arm-eabi/package.json').version
        if (bindingPackageVersion !== '1.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      try {
        return require('./node-opencv-rs.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('node-opencv-rs-win32-x64-msvc')
        const bindingPackageVersion = require('node-opencv-rs-win32-x64-msvc/package.json').version
        if (bindingPackageVersion !== '1.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./node-opencv-rs.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('node-opencv-rs-win32-ia32-msvc')
        const bindingPackageVersion = require('node-opencv-rs-win32-ia32-msvc/package.json').version
        if (bindingPackageVersion !== '1.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./node-opencv-rs.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('node-opencv-rs-win32-arm64-msvc')
        const bindingPackageVersion = require('node-opencv-rs-win32-arm64-msvc/package.json').version
        if (bindingPackageVersion !== '1.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./node-opencv-rs.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      const binding = require('node-opencv-rs-darwin-universal')
      const bindingPackageVersion = require('node-opencv-rs-darwin-universal/package.json').version
      if (bindingPackageVersion !== '1.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
        throw new Error(`Native binding package version mismatch, expected 1.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
      }
      return binding
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./node-opencv-rs.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('node-opencv-rs-darwin-x64')
        const bindingPackageVersion = require('node-opencv-rs-darwin-x64/package.json').version
        if (bindingPackageVersion !== '1.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./node-opencv-rs.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('node-opencv-rs-darwin-arm64')
        const bindingPackageVersion = require('node-opencv-rs-darwin-arm64/package.json').version
        if (bindingPackageVersion !== '1.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./node-opencv-rs.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('node-opencv-rs-freebsd-x64')
        const bindingPackageVersion = require('node-opencv-rs-freebsd-x64/package.json').version
        if (bindingPackageVersion !== '1.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./node-opencv-rs.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('node-opencv-rs-freebsd-arm64')
        const bindingPackageVersion = require('node-opencv-rs-freebsd-arm64/package.json').version
        if (bindingPackageVersion !== '1.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./node-opencv-rs.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('node-opencv-rs-linux-x64-musl')
          const bindingPackageVersion = require('node-opencv-rs-linux-x64-musl/package.json').version
          if (bindingPackageVersion !== '1.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./node-opencv-rs.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('node-opencv-rs-linux-x64-gnu')
          const bindingPackageVersion = require('node-opencv-rs-linux-x64-gnu/package.json').version
          if (bindingPackageVersion !== '1.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./node-opencv-rs.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('node-opencv-rs-linux-arm64-musl')
          const bindingPackageVersion = require('node-opencv-rs-linux-arm64-musl/package.json').version
          if (bindingPackageVersion !== '1.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./node-opencv-rs.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('node-opencv-rs-linux-arm64-gnu')
          const bindingPackageVersion = require('node-opencv-rs-linux-arm64-gnu/package.json').version
          if (bindingPackageVersion !== '1.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./node-opencv-rs.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('node-opencv-rs-linux-arm-musleabihf')
          const bindingPackageVersion = require('node-opencv-rs-linux-arm-musleabihf/package.json').version
          if (bindingPackageVersion !== '1.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./node-opencv-rs.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('node-opencv-rs-linux-arm-gnueabihf')
          const bindingPackageVersion = require('node-opencv-rs-linux-arm-gnueabihf/package.json').version
          if (bindingPackageVersion !== '1.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./node-opencv-rs.linux-loong64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('node-opencv-rs-linux-loong64-musl')
          const bindingPackageVersion = require('node-opencv-rs-linux-loong64-musl/package.json').version
          if (bindingPackageVersion !== '1.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./node-opencv-rs.linux-loong64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('node-opencv-rs-linux-loong64-gnu')
          const bindingPackageVersion = require('node-opencv-rs-linux-loong64-gnu/package.json').version
          if (bindingPackageVersion !== '1.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./node-opencv-rs.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('node-opencv-rs-linux-riscv64-musl')
          const bindingPackageVersion = require('node-opencv-rs-linux-riscv64-musl/package.json').version
          if (bindingPackageVersion !== '1.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./node-opencv-rs.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('node-opencv-rs-linux-riscv64-gnu')
          const bindingPackageVersion = require('node-opencv-rs-linux-riscv64-gnu/package.json').version
          if (bindingPackageVersion !== '1.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./node-opencv-rs.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('node-opencv-rs-linux-ppc64-gnu')
        const bindingPackageVersion = require('node-opencv-rs-linux-ppc64-gnu/package.json').version
        if (bindingPackageVersion !== '1.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./node-opencv-rs.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('node-opencv-rs-linux-s390x-gnu')
        const bindingPackageVersion = require('node-opencv-rs-linux-s390x-gnu/package.json').version
        if (bindingPackageVersion !== '1.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./node-opencv-rs.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('node-opencv-rs-openharmony-arm64')
        const bindingPackageVersion = require('node-opencv-rs-openharmony-arm64/package.json').version
        if (bindingPackageVersion !== '1.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./node-opencv-rs.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('node-opencv-rs-openharmony-x64')
        const bindingPackageVersion = require('node-opencv-rs-openharmony-x64/package.json').version
        if (bindingPackageVersion !== '1.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./node-opencv-rs.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('node-opencv-rs-openharmony-arm')
        const bindingPackageVersion = require('node-opencv-rs-openharmony-arm/package.json').version
        if (bindingPackageVersion !== '1.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
  let wasiBinding = null
  let wasiBindingError = null
  try {
    wasiBinding = require('./node-opencv-rs.wasi.cjs')
    nativeBinding = wasiBinding
  } catch (err) {
    if (process.env.NAPI_RS_FORCE_WASI) {
      wasiBindingError = err
    }
  }
  if (!nativeBinding) {
    try {
      wasiBinding = require('node-opencv-rs-wasm32-wasi')
      nativeBinding = wasiBinding
    } catch (err) {
      if (process.env.NAPI_RS_FORCE_WASI) {
        wasiBindingError.cause = err
        loadErrors.push(err)
      }
    }
  }
  if (process.env.NAPI_RS_FORCE_WASI === 'error' && !wasiBinding) {
    const error = new Error('WASI binding not found and NAPI_RS_FORCE_WASI is set to error')
    error.cause = wasiBindingError
    throw error
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
      {
        cause: loadErrors.reduce((err, cur) => {
          cur.cause = err
          return cur
        }),
      },
    )
  }
  throw new Error(`Failed to load native binding`)
}

module.exports = nativeBinding
module.exports.Mat = nativeBinding.Mat
module.exports.JSMat = nativeBinding.JSMat
module.exports.Net = nativeBinding.Net
module.exports.VideoCapture = nativeBinding.VideoCapture
module.exports.VideoWriter = nativeBinding.VideoWriter
module.exports.AdaptiveThresholdType = nativeBinding.AdaptiveThresholdType
module.exports.approxPolyDP = nativeBinding.approxPolyDP
module.exports.arcLength = nativeBinding.arcLength
module.exports.blobFromImage = nativeBinding.blobFromImage
module.exports.BorderType = nativeBinding.BorderType
module.exports.boundingRect = nativeBinding.boundingRect
module.exports.CAP_PROP_BACKEND = nativeBinding.CAP_PROP_BACKEND
module.exports.CAP_PROP_BITRATE = nativeBinding.CAP_PROP_BITRATE
module.exports.CAP_PROP_BRIGHTNESS = nativeBinding.CAP_PROP_BRIGHTNESS
module.exports.CAP_PROP_CONTRAST = nativeBinding.CAP_PROP_CONTRAST
module.exports.CAP_PROP_FORMAT = nativeBinding.CAP_PROP_FORMAT
module.exports.CAP_PROP_FOURCC = nativeBinding.CAP_PROP_FOURCC
module.exports.CAP_PROP_FPS = nativeBinding.CAP_PROP_FPS
module.exports.CAP_PROP_FRAME_COUNT = nativeBinding.CAP_PROP_FRAME_COUNT
module.exports.CAP_PROP_FRAME_HEIGHT = nativeBinding.CAP_PROP_FRAME_HEIGHT
module.exports.CAP_PROP_FRAME_WIDTH = nativeBinding.CAP_PROP_FRAME_WIDTH
module.exports.CAP_PROP_POS_FRAMES = nativeBinding.CAP_PROP_POS_FRAMES
module.exports.CAP_PROP_POS_MSEC = nativeBinding.CAP_PROP_POS_MSEC
module.exports.ColorCode = nativeBinding.ColorCode
module.exports.ContourApproximation = nativeBinding.ContourApproximation
module.exports.contourArea = nativeBinding.contourArea
module.exports.ContourRetrievalMode = nativeBinding.ContourRetrievalMode
module.exports.convexHull = nativeBinding.convexHull
module.exports.countNonZero = nativeBinding.countNonZero
module.exports.CV_16S = nativeBinding.CV_16S
module.exports.CV_16SC1 = nativeBinding.CV_16SC1
module.exports.CV_16SC3 = nativeBinding.CV_16SC3
module.exports.CV_16U = nativeBinding.CV_16U
module.exports.CV_16UC1 = nativeBinding.CV_16UC1
module.exports.CV_16UC3 = nativeBinding.CV_16UC3
module.exports.CV_32F = nativeBinding.CV_32F
module.exports.CV_32FC1 = nativeBinding.CV_32FC1
module.exports.CV_32FC3 = nativeBinding.CV_32FC3
module.exports.CV_32S = nativeBinding.CV_32S
module.exports.CV_32SC1 = nativeBinding.CV_32SC1
module.exports.CV_64F = nativeBinding.CV_64F
module.exports.CV_64FC1 = nativeBinding.CV_64FC1
module.exports.CV_64FC3 = nativeBinding.CV_64FC3
module.exports.CV_8S = nativeBinding.CV_8S
module.exports.CV_8U = nativeBinding.CV_8U
module.exports.CV_8UC1 = nativeBinding.CV_8UC1
module.exports.CV_8UC2 = nativeBinding.CV_8UC2
module.exports.CV_8UC3 = nativeBinding.CV_8UC3
module.exports.CV_8UC4 = nativeBinding.CV_8UC4
module.exports.DnnBackend = nativeBinding.DnnBackend
module.exports.DnnTarget = nativeBinding.DnnTarget
module.exports.drawCircle = nativeBinding.drawCircle
module.exports.drawContours = nativeBinding.drawContours
module.exports.drawEllipse = nativeBinding.drawEllipse
module.exports.drawLine = nativeBinding.drawLine
module.exports.drawRectangle = nativeBinding.drawRectangle
module.exports.fillPoly = nativeBinding.fillPoly
module.exports.FlipCode = nativeBinding.FlipCode
module.exports.FONT_ITALIC = nativeBinding.FONT_ITALIC
module.exports.getAffineTransform = nativeBinding.getAffineTransform
module.exports.getBuildInformation = nativeBinding.getBuildInformation
module.exports.getPerspectiveTransform = nativeBinding.getPerspectiveTransform
module.exports.getRotationMatrix2D = nativeBinding.getRotationMatrix2D
module.exports.getStructuringElement = nativeBinding.getStructuringElement
module.exports.getTextSize = nativeBinding.getTextSize
module.exports.getTickCount = nativeBinding.getTickCount
module.exports.getTickFrequency = nativeBinding.getTickFrequency
module.exports.hconcat = nativeBinding.hconcat
module.exports.HersheyFont = nativeBinding.HersheyFont
module.exports.HoughMethod = nativeBinding.HoughMethod
module.exports.imdecode = nativeBinding.imdecode
module.exports.imencode = nativeBinding.imencode
module.exports.imread = nativeBinding.imread
module.exports.ImreadFlag = nativeBinding.ImreadFlag
module.exports.imwrite = nativeBinding.imwrite
module.exports.InterpolationFlag = nativeBinding.InterpolationFlag
module.exports.LineType = nativeBinding.LineType
module.exports.mean = nativeBinding.mean
module.exports.merge = nativeBinding.merge
module.exports.minAreaRect = nativeBinding.minAreaRect
module.exports.MorphShape = nativeBinding.MorphShape
module.exports.MorphType = nativeBinding.MorphType
module.exports.nmsBoxes = nativeBinding.nmsBoxes
module.exports.NormType = nativeBinding.NormType
module.exports.putText = nativeBinding.putText
module.exports.TemplateMatchMode = nativeBinding.TemplateMatchMode
module.exports.ThresholdType = nativeBinding.ThresholdType
module.exports.vconcat = nativeBinding.vconcat
module.exports.WARP_FILL_OUTLIERS = nativeBinding.WARP_FILL_OUTLIERS
module.exports.WARP_INVERSE_MAP = nativeBinding.WARP_INVERSE_MAP
