/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Mat {
  constructor()
  static zeros(rows: number, cols: number, matType: number): Mat
  static ones(rows: number, cols: number, matType: number): Mat
  static eye(rows: number, cols: number, matType: number): Mat
  static fromBuffer(rows: number, cols: number, matType: number, buffer: Buffer): Mat
  get rows(): number
  get cols(): number
  get channels(): number
  get matType(): number
  get depth(): number
  get empty(): boolean
  get size(): Size
  get total(): number
  get elemSize(): number
  get data(): Buffer
  clone(): Mat
  copyTo(dst: Mat): void
  convertTo(rtype: number, alpha?: number | undefined | null, beta?: number | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  reshape(cn: number, rows?: number | undefined | null): Mat
  matchTemplate(template: Mat, method: TemplateMatchMode, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  matchTemplateAll(template: Mat, method: TemplateMatchMode, score: number, nmsThreshold: number, abortSignal?: AbortSignal | undefined | null): Promise<Array<Rect>>
  minMaxLoc(abortSignal?: AbortSignal | undefined | null): Promise<MinMaxResult>
  threshold(thresh: number, maxval: number, typ: ThresholdType, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  cvtColor(code: ColorCode, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  resize(width: number, height: number, fx?: number | undefined | null, fy?: number | undefined | null, interpolation?: InterpolationFlag | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  gaussianBlur(ksizeWidth: number, ksizeHeight: number, sigmaX: number, sigmaY?: number | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  canny(threshold1: number, threshold2: number, apertureSize?: number | undefined | null, l2Gradient?: boolean | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  dilate(kernel: Mat, iterations?: number | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  erode(kernel: Mat, iterations?: number | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  morphologyEx(op: MorphType, kernel: Mat, iterations?: number | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  warpAffine(m: Mat, dstWidth: number, dstHeight: number, flags?: number | undefined | null, borderMode?: BorderType | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  flip(flipCode: FlipCode, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  crop(x: number, y: number, width: number, height: number, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  inRange(lower: Scalar, upper: Scalar, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  bitwiseAnd(other: Mat, mask?: Mat | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  bitwiseOr(other: Mat, mask?: Mat | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  bitwiseNot(mask?: Mat | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  bitwiseXor(other: Mat, mask?: Mat | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  split(abortSignal?: AbortSignal | undefined | null): Promise<Array<Mat>>
  normalize(alpha?: number | undefined | null, beta?: number | undefined | null, normType?: NormType | undefined | null, dtype?: number | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  addWeighted(alpha: number, src2: Mat, beta: number, gamma: number, dtype?: number | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  medianBlur(ksize: number, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  bilateralFilter(d: number, sigmaColor: number, sigmaSpace: number, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  sobel(ddepth: number, dx: number, dy: number, ksize?: number | undefined | null, scale?: number | undefined | null, delta?: number | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  laplacian(ddepth: number, ksize?: number | undefined | null, scale?: number | undefined | null, delta?: number | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  equalizeHist(abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  copyMakeBorder(top: number, bottom: number, left: number, right: number, borderType: BorderType, value?: Array<number> | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  filter2D(ddepth: number, kernel: Mat, delta?: number | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  absDiff(other: Mat, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  add(other: Mat, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  subtract(other: Mat, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  multiply(other: Mat, scale?: number | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  warpPerspective(m: Mat, dstWidth: number, dstHeight: number, flags?: number | undefined | null, borderMode?: BorderType | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  transpose(abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  release(): void
  findContours(mode: ContourRetrievalMode, method: ContourApproximation, abortSignal?: AbortSignal | undefined | null): Promise<Array<Array<Point>>>
  goodFeaturesToTrack(maxCorners: number, qualityLevel: number, minDistance: number, blockSize?: number | undefined | null, useHarris?: boolean | undefined | null, k?: number | undefined | null, mask?: Mat | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<Array<PointF64>>
  houghCircles(dp: number, minDist: number, param1?: number | undefined | null, param2?: number | undefined | null, minRadius?: number | undefined | null, maxRadius?: number | undefined | null, method?: HoughMethod | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<Array<Circle>>
  houghLines(rho: number, theta: number, threshold: number, abortSignal?: AbortSignal | undefined | null): Promise<Array<HoughLine>>
  houghLinesP(rho: number, theta: number, threshold: number, minLineLength?: number | undefined | null, maxLineGap?: number | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<Array<LineSegment>>
  adaptiveThreshold(maxValue: number, adaptiveMethod: AdaptiveThresholdType, thresholdType: ThresholdType, blockSize: number, c: number, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  moments(binaryImage?: boolean | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<MomentsResult>
}
export type JSMat = Mat

export declare class Net {
  static readNetFromOnnx(path: string): Net
  static readNetFromCaffe(protoPath: string, modelPath: string): Net
  static readNetFromDarknet(cfgPath: string, weightsPath: string): Net
  setPreferableBackend(backendId: DnnBackend): void
  setPreferableTarget(targetId: DnnTarget): void
  getUnconnectedOutLayersNames(): Array<string>
  run(blob: JSMat, inputName?: string | undefined | null, outputName?: string | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<JSMat>
  runMultiple(blob: JSMat, inputName: string | undefined | null, outputNames: Array<string>, abortSignal?: AbortSignal | undefined | null): Promise<Array<JSMat>>
}

export declare class VideoCapture {
  static open(source: string | number): VideoCapture
  isOpened(): boolean
  read(abortSignal?: AbortSignal | undefined | null): Promise<Mat | null>
  get(propId: number): number
  set(propId: number, value: number): boolean
  release(): void
}

export declare class VideoWriter {
  static open(filename: string, fourcc: string, fps: number, width: number, height: number, isColor?: boolean | undefined | null): VideoWriter
  isOpened(): boolean
  write(frame: Mat, abortSignal?: AbortSignal | undefined | null): Promise<void>
  release(): void
}

export declare const enum AdaptiveThresholdType {
  MeanC = 0,
  GaussianC = 1
}

export declare function approxPolyDP(contour: Array<Point>, epsilon: number, closed: boolean): Array<Point>

export declare function arcLength(contour: Array<Point>, closed: boolean): number

export declare function blobFromImage(image: JSMat, scaleFactor?: number | undefined | null, width?: number | undefined | null, height?: number | undefined | null, mean?: Array<number> | undefined | null, swapRb?: boolean | undefined | null, crop?: boolean | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<JSMat>

export declare const enum BorderType {
  Constant = 0,
  Replicate = 1,
  Reflect = 2,
  Wrap = 3,
  Reflect101 = 4,
  Transparent = 5,
  Isolated = 16
}

export declare function boundingRect(contour: Array<Point>): Rect

export const CAP_PROP_BACKEND: number

export const CAP_PROP_BITRATE: number

export const CAP_PROP_BRIGHTNESS: number

export const CAP_PROP_CONTRAST: number

export const CAP_PROP_FORMAT: number

export const CAP_PROP_FOURCC: number

export const CAP_PROP_FPS: number

export const CAP_PROP_FRAME_COUNT: number

export const CAP_PROP_FRAME_HEIGHT: number

export const CAP_PROP_FRAME_WIDTH: number

export const CAP_PROP_POS_FRAMES: number

export const CAP_PROP_POS_MSEC: number

export interface Circle {
  x: number
  y: number
  radius: number
}

export declare const enum ColorCode {
  Bgr2Bgra = 0,
  Bgra2Bgr = 1,
  Bgr2Rgba = 2,
  Rgba2Bgr = 3,
  Bgr2Rgb = 4,
  Bgra2Rgba = 5,
  Bgr2Gray = 6,
  Rgb2Gray = 7,
  Gray2Bgr = 8,
  Gray2Bgra = 9,
  Bgr2Xyz = 32,
  Xyz2Bgr = 34,
  Bgr2YCrCb = 36,
  YCrCb2Bgr = 38,
  Bgr2Hsv = 40,
  Bgr2Lab = 44,
  Bgr2Hls = 52,
  Hsv2Bgr = 54,
  Lab2Bgr = 56,
  Hls2Bgr = 60
}

export declare const enum ContourApproximation {
  None = 1,
  Simple = 2,
  Tc89L1 = 3,
  Tc89Kcos = 4
}

export declare function contourArea(contour: Array<Point>): number

export declare const enum ContourRetrievalMode {
  External = 0,
  List = 1,
  CComp = 2,
  Tree = 3
}

export declare function convexHull(points: Array<Point>): Array<Point>

export declare function countNonZero(mat: Mat, abortSignal?: AbortSignal | undefined | null): Promise<number>

export const CV_16S: number

export const CV_16SC1: number

export const CV_16SC3: number

export const CV_16U: number

export const CV_16UC1: number

export const CV_16UC3: number

export const CV_32F: number

export const CV_32FC1: number

export const CV_32FC3: number

export const CV_32S: number

export const CV_32SC1: number

export const CV_64F: number

export const CV_64FC1: number

export const CV_64FC3: number

export const CV_8S: number

export const CV_8U: number

export const CV_8UC1: number

export const CV_8UC2: number

export const CV_8UC3: number

export const CV_8UC4: number

export declare const enum DnnBackend {
  Default = 0,
  Halide = 1,
  InferenceEngine = 2,
  OpenCv = 3,
  Vkcom = 4,
  Cuda = 5,
  Webnn = 6,
  Timvx = 7
}

export declare const enum DnnTarget {
  Cpu = 0,
  OpenCl = 1,
  OpenClFp16 = 2,
  Myriad = 3,
  Vulkan = 4,
  Fpga = 5,
  Cuda = 6,
  CudaFp16 = 7,
  Hddl = 8,
  Npu = 9
}

export declare function drawCircle(mat: JSMat, center: Point, radius: number, color: Scalar, thickness?: number | undefined | null, lineType?: LineType | undefined | null): void

export declare function drawContours(mat: JSMat, contours: Array<Array<Point>>, contourIdx: number, color: Scalar, thickness?: number | undefined | null, lineType?: LineType | undefined | null, maxLevel?: number | undefined | null): void

export declare function drawEllipse(mat: JSMat, center: Point, axes: Size, angle: number, startAngle: number, endAngle: number, color: Scalar, thickness?: number | undefined | null, lineType?: LineType | undefined | null): void

export declare function drawLine(mat: JSMat, pt1: Point, pt2: Point, color: Scalar, thickness?: number | undefined | null, lineType?: LineType | undefined | null): void

export declare function drawRectangle(mat: JSMat, rect: Rect, color: Scalar, thickness?: number | undefined | null, lineType?: LineType | undefined | null): void

export declare function fillPoly(mat: JSMat, pts: Array<Array<Point>>, color: Scalar, lineType?: LineType | undefined | null): void

export declare const enum FlipCode {
  Vertical = 0,
  Horizontal = 1,
  Both = -1
}

export const FONT_ITALIC: number

export declare function getAffineTransform(srcPts: Array<PointF64>, dstPts: Array<PointF64>, abortSignal?: AbortSignal | undefined | null): Promise<Mat>

export declare function getBuildInformation(): string

export declare function getPerspectiveTransform(srcPts: Array<PointF64>, dstPts: Array<PointF64>, abortSignal?: AbortSignal | undefined | null): Promise<Mat>

export declare function getRotationMatrix2D(centerX: number, centerY: number, angle: number, scale: number): Mat

export declare function getStructuringElement(shape: MorphShape, ksizeWidth: number, ksizeHeight: number): Mat

export declare function getTextSize(text: string, fontFace: HersheyFont, fontScale: number, thickness?: number | undefined | null): TextSize

export declare function getTickCount(): number

export declare function getTickFrequency(): number

export declare function hconcat(mats: Array<Mat>, abortSignal?: AbortSignal | undefined | null): Promise<Mat>

export declare const enum HersheyFont {
  Simplex = 0,
  Plain = 1,
  Duplex = 2,
  Complex = 3,
  Triplex = 4,
  ComplexSmall = 5,
  ScriptSimplex = 6,
  ScriptComplex = 7,
  SimplexItalic = 16,
  PlainItalic = 17,
  DuplexItalic = 18,
  ComplexItalic = 19,
  TriplexItalic = 20,
  ComplexSmallItalic = 21,
  ScriptSimplexItalic = 22,
  ScriptComplexItalic = 23
}

export interface HoughLine {
  rho: number
  theta: number
}

export declare const enum HoughMethod {
  Gradient = 3,
  GradientAlt = 4
}

export declare function imdecode(buffer: Buffer, flags?: ImreadFlag | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<Mat>

export declare function imencode(ext: string, mat: Mat, abortSignal?: AbortSignal | undefined | null): Promise<Buffer>

export declare function imread(path: string, flags?: ImreadFlag | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<Mat>

export declare const enum ImreadFlag {
  Unchanged = -1,
  Grayscale = 0,
  Color = 1,
  AnyDepth = 2,
  AnyColor = 4,
  LoadGdal = 8,
  ReducedGrayscale2 = 16,
  ReducedColor2 = 17,
  ReducedGrayscale4 = 32,
  ReducedColor4 = 33,
  ReducedGrayscale8 = 64,
  ReducedColor8 = 65,
  IgnoreOrientation = 128
}

export declare function imwrite(path: string, mat: Mat, abortSignal?: AbortSignal | undefined | null): Promise<boolean>

export declare const enum InterpolationFlag {
  Nearest = 0,
  Linear = 1,
  Cubic = 2,
  Area = 3,
  Lanczos4 = 4,
  LinearExact = 5,
  NearestExact = 6
}

export interface KeyPoint {
  pt: PointF64
  size: number
  angle: number
  response: number
  octave: number
  classId: number
}

export interface LineSegment {
  x1: number
  y1: number
  x2: number
  y2: number
}

export declare const enum LineType {
  Line4 = 4,
  Line8 = 8,
  AntiAlias = 16
}

export declare function mean(mat: Mat, abortSignal?: AbortSignal | undefined | null): Promise<Array<number>>

export declare function merge(channels: Array<Mat>, abortSignal?: AbortSignal | undefined | null): Promise<Mat>

export declare function minAreaRect(contour: Array<Point>): RotatedRect

export interface MinMaxResult {
  minVal: number
  maxVal: number
  minLoc: Point
  maxLoc: Point
}

export interface MomentsResult {
  m00: number
  m10: number
  m01: number
  m20: number
  m11: number
  m02: number
  m30: number
  m21: number
  m12: number
  m03: number
  mu20: number
  mu11: number
  mu02: number
  mu30: number
  mu21: number
  mu12: number
  mu03: number
  nu20: number
  nu11: number
  nu02: number
  nu30: number
  nu21: number
  nu12: number
  nu03: number
}

export declare const enum MorphShape {
  Rect = 0,
  Cross = 1,
  Ellipse = 2
}

export declare const enum MorphType {
  Erode = 0,
  Dilate = 1,
  Open = 2,
  Close = 3,
  Gradient = 4,
  TopHat = 5,
  BlackHat = 6,
  HitMiss = 7
}

export declare function nmsBoxes(bboxes: Array<Rect>, scores: Array<number>, scoreThreshold: number, nmsThreshold: number, abortSignal?: AbortSignal | undefined | null): Promise<Array<number>>

export declare const enum NormType {
  Inf = 1,
  L1 = 2,
  L2 = 4,
  L2Sqr = 5,
  Hamming = 6,
  Hamming2 = 7,
  MinMax = 32
}

export interface Point {
  x: number
  y: number
}

export interface PointF64 {
  x: number
  y: number
}

export declare function putText(mat: JSMat, text: string, org: Point, fontFace: HersheyFont, fontScale: number, color: Scalar, thickness?: number | undefined | null, lineType?: LineType | undefined | null): void

export interface Rect {
  x: number
  y: number
  width: number
  height: number
}

export interface RotatedRect {
  center: PointF64
  size: SizeF64
  angle: number
}

export interface Scalar {
  v0: number
  v1: number
  v2: number
  v3: number
}

export interface Size {
  width: number
  height: number
}

export interface SizeF64 {
  width: number
  height: number
}

export declare const enum TemplateMatchMode {
  Sqdiff = 0,
  SqdiffNormed = 1,
  Ccorr = 2,
  CcorrNormed = 3,
  Ccoeff = 4,
  CcoeffNormed = 5
}

export interface TextSize {
  width: number
  height: number
  baseline: number
}

export declare const enum ThresholdType {
  Binary = 0,
  BinaryInv = 1,
  Trunc = 2,
  ToZero = 3,
  ToZeroInv = 4,
  Otsu = 8,
  Triangle = 16
}

export declare function vconcat(mats: Array<Mat>, abortSignal?: AbortSignal | undefined | null): Promise<Mat>

export const WARP_FILL_OUTLIERS: number

export const WARP_INVERSE_MAP: number
