/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Dnn {
  constructor()
  nmsBoxes(bboxes: Array<Rect>, scores: Array<number>, scoreThreshold: number, nmsThreshold: number, abortSignal?: AbortSignal | undefined | null): Promise<Array<number>>
}
export type DNN = Dnn

export declare class Mat {
  constructor()
  get rows(): number
  get cols(): number
  get size(): Size
  get data(): Buffer
  matchTemplate(template: Mat, method: number, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  minMaxLoc(abortSignal?: AbortSignal | undefined | null): Promise<MinMaxResult>
  threshold(thresh: number, maxval: number, typ: number, abortSignal?: AbortSignal | undefined | null): Promise<Mat>
  matchTemplateAll(template: Mat, method: number, score: number, nmsThreshold: number, abortSignal?: AbortSignal | undefined | null): Promise<Array<Rect>>
  release(): void
}
export type JSMat = Mat

export declare function getBuildInformation(): string

export declare function getTickCount(): number

export declare function getTickFrequency(): number

export declare function imdecode(buffer: Buffer, flags?: number | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<JSMat>

export declare function imencode(ext: string, mat: JSMat, abortSignal?: AbortSignal | undefined | null): Promise<Buffer>

export declare function imread(path: string, flags?: number | undefined | null, abortSignal?: AbortSignal | undefined | null): Promise<JSMat>

export const IMREAD_ANYCOLOR: number

export const IMREAD_ANYDEPTH: number

export const IMREAD_COLOR: number

export const IMREAD_GRAYSCALE: number

export const IMREAD_IGNORE_ORIENTATION: number

export const IMREAD_LOAD_GDAL: number

export const IMREAD_REDUCED_COLOR_2: number

export const IMREAD_REDUCED_COLOR_4: number

export const IMREAD_REDUCED_COLOR_8: number

export const IMREAD_REDUCED_GRAYSCALE_2: number

export const IMREAD_REDUCED_GRAYSCALE_4: number

export const IMREAD_REDUCED_GRAYSCALE_8: number

export const IMREAD_UNCHANGED: number

export interface MinMaxResult {
  minVal: number
  maxVal: number
  minLoc: Point
  maxLoc: Point
}

export interface Point {
  x: number
  y: number
}

export interface Rect {
  x: number
  y: number
  width: number
  height: number
}

export interface Rect {
  x: number
  y: number
  width: number
  height: number
}

export interface Size {
  width: number
  height: number
}

export const TM_CCOEFF: number

export const TM_CCOEFF_NORMED: number

export const TM_CCORR: number

export const TM_CCORR_NORMED: number

export const TM_SQDIFF: number

export const TM_SQDIFF_NORMED: number
