/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Size {
  width: number
  height: number
}
export interface MinMaxResult {
  minVal: number
  maxVal: number
  minX: number
  minY: number
  maxX: number
  maxY: number
}
export declare function getTickFrequency(): number
export declare function getBuildInformation(): string
export declare function getTickCount(): number
export declare function imread(path: string): Mat
export declare function imreadCallback(path: string, callback: (...args: any[]) => any): void
export declare function imreadAsync(path: string): Promise<Mat>
export declare function imdecode(buffer: Buffer): Mat
export declare function imdecodeCallback(buffer: Buffer, callback: (...args: any[]) => any): void
export declare function imdecodeAsync(buffer: Buffer): Promise<Mat>
export const TM_SQDIFF: number
export const TM_SQDIFF_NORMED: number
export const TM_CCORR: number
export const TM_CCORR_NORMED: number
export const TM_CCOEFF: number
export const TM_CCOEFF_NORMED: number
export const IMREAD_UNCHANGED: number
export const IMREAD_GRAYSCALE: number
export const IMREAD_COLOR: number
export const IMREAD_ANYDEPTH: number
export const IMREAD_ANYCOLOR: number
export const IMREAD_LOAD_GDAL: number
export const IMREAD_REDUCED_GRAYSCALE_2: number
export const IMREAD_REDUCED_COLOR_2: number
export const IMREAD_REDUCED_GRAYSCALE_4: number
export const IMREAD_REDUCED_COLOR_4: number
export const IMREAD_REDUCED_GRAYSCALE_8: number
export const IMREAD_REDUCED_COLOR_8: number
export const IMREAD_IGNORE_ORIENTATION: number
export type JSMat = Mat
export declare class Mat {
  constructor()
  get rows(): number
  get cols(): number
  get size(): Size
  get data(): Buffer
  matchTemplateCallback(template: Mat, method: number, callback: (...args: any[]) => any): void
  matchTemplateAsync(template: Mat, method: number): Promise<MinMaxResult>
  minMaxLocCallback(callback: (...args: any[]) => any): void
  minMaxLocAsync(): Promise<MinMaxResult>
  release(): void
}
