/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Size {
  width: number
  height: number
}
export interface Point {
  x: number
  y: number
}
export interface MinMaxResult {
  minVal: number
  maxVal: number
  minLoc: Point
  maxLoc: Point
}
export interface Rect {
  x: number
  y: number
  width: number
  height: number
}
export declare function getTickFrequency(): number
export declare function getBuildInformation(): string
export declare function getTickCount(): number
export declare function imread(path: string): Mat
export declare function imreadCallback(path: string, callback: (...args: any[]) => any): void
export declare function imreadAsync(path: string): Promise<Mat>
export declare function imdecode(buffer: Buffer): Mat
export declare function imdecodeCallback(buffer: Buffer, callback: (...args: any[]) => any): void
export declare function imdecodeAsync(buffer: Buffer): Promise<Mat>
export declare function imencode(ext: string, mat: JSMat): Buffer
export declare function imencodeCallback(ext: string, mat: JSMat, callback: (...args: any[]) => any): void
export declare function imencodeAsync(ext: string, mat: JSMat): Promise<Buffer>
export const TM_SQDIFF: number
export const TM_SQDIFF_NORMED: number
export const TM_CCORR: number
export const TM_CCORR_NORMED: number
export const TM_CCOEFF: number
export const TM_CCOEFF_NORMED: number
export const IMREAD_UNCHANGED: number
export const IMREAD_GRAYSCALE: number
export const IMREAD_COLOR: number
export const IMREAD_ANYDEPTH: number
export const IMREAD_ANYCOLOR: number
export const IMREAD_LOAD_GDAL: number
export const IMREAD_REDUCED_GRAYSCALE_2: number
export const IMREAD_REDUCED_COLOR_2: number
export const IMREAD_REDUCED_GRAYSCALE_4: number
export const IMREAD_REDUCED_COLOR_4: number
export const IMREAD_REDUCED_GRAYSCALE_8: number
export const IMREAD_REDUCED_COLOR_8: number
export const IMREAD_IGNORE_ORIENTATION: number
export type JSMat = Mat
export declare class Mat {
  constructor()
  get rows(): number
  get cols(): number
  get size(): Size
  get data(): Buffer
  matchTemplateAllCallback(template: Mat, method: number, score: number, nmsThreshold: number, callback: (...args: any[]) => any): void
  matchTemplateAllAsync(template: Mat, method: number, score: number, nmsThreshold: number): Promise<Array<Rect>>
  matchTemplateCallback(template: Mat, method: number, callback: (...args: any[]) => any): void
  matchTemplateAsync(template: Mat, method: number): Promise<Mat>
  minMaxLocCallback(callback: (...args: any[]) => any): void
  minMaxLocAsync(): Promise<MinMaxResult>
  release(): void
}
export type DNN = Dnn
export declare class Dnn {
  constructor()
  nmsBoxes(bboxes: Array<Rect>, scores: Array<number>, scoreThreshold: number, nmsThreshold: number, callback: (...args: any[]) => any): void
}
