name: Linux Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake
        sudo apt-get install -y libopencv-dev

    - name: Set Environment Variables
      run: |
          echo "OPENCV_INCLUDE_DIR=D:/opencv/build/include" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "OPENCV_LIB_DIR=D:/opencv/build/x64/vc16/lib" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "D:/opencv/build/x64/vc16/bin" | Out-File -FilePath $env:GITHUB_PATH -Append

    - name: Install dependencies and build
      run: npm install

    - name: Test
      run: npm test --if-present
